In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve
from sklearn.model_selection import train_test_split, learning_curve
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve
from sklearn.model_selection import train_test_split, learning_curve
from sklearn.model_selection import train_test_split
from scipy import stats
import numpy as np
from sklearn.ensemble import VotingClassifier

In [ ]:
df=pd.read_csv('Y_Train_Data_Target.csv')

In [ ]:
df1=pd.read_csv('X_Train_Data_Input.csv')

In [ ]:
cdf=pd.read_csv('Y_Test_Data_Target.csv')

In [ ]:
cdf1=pd.read_csv('X_Test_Data_Input.csv')

In [ ]:
df.shape

(785133, 2)

In [ ]:
cdf1.shape

(261712, 23)

In [ ]:
training_df = pd.merge(df1, df, on='ID', how='left')

In [ ]:
training_df.shape

(785133, 24)

In [ ]:
testing_df = pd.merge(cdf1, cdf, on='ID', how='left')

In [ ]:
testing_df.shape

(261712, 24)

In [ ]:
training_df.head()

ID  Column0  Column1  Column2   Column3  \
0  ad1a67e4cbddc767a3456b0d94299b9e      2.0     2495   3726.0  0.678139   
1  7246d2f76ac0c217ec25e72ea5f014cb      0.0     2495   3454.0  0.452580   
2  22ba388e7dd14c13342c49e75fc29dda      2.0     2495   4543.0 -1.577453   
3  59f9b981472d97342587fb3e6392aeb1      0.0      211     59.0       NaN   
4  f6317cf7ecf126859804eddff279aead      0.0      718    950.0 -2.028572   

    Column4   Column5   Column6   Column7   Column8  ...  Column13  Column14  \
0  0.701403 -0.007468  0.434190 -0.015603  0.606265  ...         0  0.001351   
1  0.701403 -0.007468  1.554998 -0.015574  0.329946  ...         0  0.001351   
2 -1.429540 -0.007469 -0.407939 -0.015607 -0.774979  ...         1  0.001351   
3       NaN       NaN -0.407939 -0.015607 -0.774979  ...         0       NaN   
4 -1.855728       NaN -0.407939 -0.015607 -0.774979  ...         0       NaN   

   Column15  Column16  Column17  Column18  Column19  Column20  Column21  \
0   0.00339       0.0         0       0.0         0         0         0   
1   0.00339       0.0         0       0.0         0         0         0   
2   0.00339       0.0         0       0.0         0         0         0   
3   0.00339       0.0         0       1.0         0         0         0   
4   0.00339       0.0         0       0.0         0         0         0   

   target  
0       0  
1       0  
2       0  
3       1  
4       0  

[5 rows x 24 columns]

In [ ]:
testing_df.head()

ID  Column0  Column1  Column2   Column3  \
0  07cf2025382f6325b316e128b1b90999      1.0     1986     53.0  0.678139   
1  eb972eb3a1f8d0d1a13f45e7c07d37d4      2.0     1579     12.0  0.678139   
2  ee35e164b3ddc25a9f40243b81ad290d      0.0      898   3817.0 -2.028572   
3  28229ccd7bad7dd83324a4175a7e0531      0.0       79   3449.0 -0.675216   
4  2f94873da2c332d28f111742818e0fbb      1.0      646   6510.0 -2.028572   

    Column4   Column5   Column6   Column7   Column8  ...  Column13  Column14  \
0  0.701403 -0.007469 -0.407939 -0.015607  0.554860  ...         1  0.001351   
1  0.701403 -0.007468 -0.407939 -0.015607  0.142149  ...         0  0.001351   
2 -1.855728       NaN -0.407939 -0.015607 -0.774979  ...         0       NaN   
3 -0.577162 -0.007469  0.004020 -0.015607  0.635264  ...         1  0.001351   
4 -1.855728       NaN -0.407939 -0.015434 -0.774979  ...         1       NaN   

   Column15  Column16  Column17  Column18  Column19  Column20  Column21  \
0   0.00339       0.0         0       0.0         0         0         0   
1   0.00339       0.0         0       0.0         0         0         0   
2   0.00339       0.0         0       0.0         0         0         0   
3   0.00339       0.0         0       0.0         0         0         0   
4   0.00339       0.0         0       0.0         0         0         0   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

[5 rows x 24 columns]

In [ ]:
testing_df.isnull().sum()

ID               0
Column0          2
Column1          0
Column2          0
Column3      42234
Column4      42710
Column5      55659
Column6       1234
Column7          0
Column8       1234
Column9     243853
Column10         0
Column11         0
Column12         0
Column13         0
Column14    121679
Column15      5485
Column16         0
Column17         0
Column18         0
Column19         0
Column20         0
Column21         0
target           0
dtype: int64

In [ ]:
training_df = training_df.drop('Column9', axis=1)
testing_df = testing_df.drop('Column9', axis=1)

In [ ]:
columns_to_interpolate = ['Column3', 'Column4', 'Column5', 'Column6', 'Column8', 'Column14', 'Column15']

In [ ]:
training_df.dropna(subset=['Column0'], inplace=True)
testing_df.dropna(subset=['Column0'], inplace=True)

In [ ]:
training_df[columns_to_interpolate] = training_df[columns_to_interpolate].interpolate(method='linear', axis=0)
testing_df[columns_to_interpolate] = testing_df[columns_to_interpolate].interpolate(method='linear', axis=0)

In [ ]:
training_df.shape

(785124, 23)

In [ ]:
numeric_columns = training_df.select_dtypes(include=[np.number]).columns.tolist()
numeric_columns.remove('target')  # Remove target from numeric columns
z_scores = np.abs(stats.zscore(training_df[numeric_columns]))
threshold = 3

# Identify rows where Z-score is less than the threshold across all numeric columns
outliers = (z_scores < threshold).all(axis=1)

# Remove outliers from the training dataframe
training_df_cleaned = training_df[outliers]

In [ ]:
print(f"Original data size: {training_df.shape}")
print(f"Data size after removing outliers: {training_df_cleaned.shape}")

Original data size: (785124, 23)
Data size after removing outliers: (689548, 23)


In [ ]:
training_df_cleaned.head()

ID  Column0  Column1  Column2   Column3  \
0  ad1a67e4cbddc767a3456b0d94299b9e      2.0     2495   3726.0  0.678139   
1  7246d2f76ac0c217ec25e72ea5f014cb      0.0     2495   3454.0  0.452580   
2  22ba388e7dd14c13342c49e75fc29dda      2.0     2495   4543.0 -1.577453   
3  59f9b981472d97342587fb3e6392aeb1      0.0      211     59.0 -1.803013   
4  f6317cf7ecf126859804eddff279aead      0.0      718    950.0 -2.028572   

    Column4   Column5   Column6   Column7   Column8  ...  Column13  Column14  \
0  0.701403 -0.007468  0.434190 -0.015603  0.606265  ...         0  0.001351   
1  0.701403 -0.007468  1.554998 -0.015574  0.329946  ...         0  0.001351   
2 -1.429540 -0.007469 -0.407939 -0.015607 -0.774979  ...         1  0.001351   
3 -1.642634 -0.007469 -0.407939 -0.015607 -0.774979  ...         0  0.001351   
4 -1.855728 -0.007469 -0.407939 -0.015607 -0.774979  ...         0  0.001351   

   Column15  Column16  Column17  Column18  Column19  Column20  Column21  \
0   0.00339       0.0         0       0.0         0         0         0   
1   0.00339       0.0         0       0.0         0         0         0   
2   0.00339       0.0         0       0.0         0         0         0   
3   0.00339       0.0         0       1.0         0         0         0   
4   0.00339       0.0         0       0.0         0         0         0   

   target  
0       0  
1       0  
2       0  
3       1  
4       0  

[5 rows x 23 columns]

In [ ]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

# Separating features and target
X =training_df_cleaned.drop(columns=['ID', 'target'])
y =training_df_cleaned['target']

# Apply SMOTE to balance the target variable
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print("After SMOTE oversampling:")
print(y_resampled.value_counts())


After SMOTE oversampling:
target
0    636660
1    636660
Name: count, dtype: int64


In [ ]:
y.value_counts()

target
0    636660
1     52888
Name: count, dtype: int64

In [ ]:
y_resampled.value_counts()

target
0    636660
1    636660
Name: count, dtype: int64

In [ ]:
# Prepare the testing dataset by dropping 'ID' column
X_test = testing_df.drop(columns=['ID'])


## 1. Decision Tree

In [ ]:
# Initialize and train the Decision Tree
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_resampled, y_resampled)

DecisionTreeClassifier(random_state=42)

In [ ]:
joblib.dump(decision_tree, 'decision_tree_model.pkl')

['decision_tree_model.pkl']

In [ ]:

#joblib.dump(decision_tree, 'decision_tree_model.pkl')
# Assuming your testing_df is already loaded and cleaned
X_test = testing_df.drop(columns=['ID', 'target'])  # Remove ID and target from test features
y_test = testing_df['target']  # Use the target column for test labels

# Load the saved Decision Tree model
loaded_decision_tree = joblib.load('decision_tree_model.pkl')

# Predict on testing data
y_test_pred = loaded_decision_tree.predict(X_test)

# Calculate prediction probabilities for AUC-ROC score
y_test_pred_proba = loaded_decision_tree.predict_proba(X_test)[:, 1]

# Evaluate the performance on the test set
accuracy = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
classification_rep = classification_report(y_test, y_test_pred)
roc_auc = roc_auc_score(y_test, y_test_pred_proba)

# Output the results
print("Confusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(classification_rep)

print(f"\nTesting Accuracy: {accuracy}")
print(f"Testing AUC-ROC Score: {roc_auc}")


Confusion Matrix:
[[232171   4861]
 [  3617  21061]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98    237032
           1       0.81      0.85      0.83     24678

    accuracy                           0.97    261710
   macro avg       0.90      0.92      0.91    261710
weighted avg       0.97      0.97      0.97    261710


Testing Accuracy: 0.9676053647166711
Testing AUC-ROC Score: 0.9166553074434725


Training dataset with a validation set

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
decision_tree.fit(X_train, y_train)

#Predict on the validation set
y_val_pred = decision_tree.predict(X_val)


print("Validation Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Validation Classification Report:")
print(classification_report(y_val, y_val_pred))

# AUC-ROC Score
y_val_proba = decision_tree.predict_proba(X_val)[:, 1]
print("Validation AUC-ROC Score:", roc_auc_score(y_val, y_val_proba))
import joblib
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
joblib.dump(decision_tree, 'decision_tree_modelv.pkl')
# Assuming your testing_df is already loaded and cleaned
X_test = testing_df.drop(columns=['ID', 'target'])  # Remove ID and target from test features
y_test = testing_df['target']  # Use the target column for test labels

# Load the saved Decision Tree model
loaded_decision_tree = joblib.load('decision_tree_modelv.pkl')

# Predict on testing data
y_test_pred = loaded_decision_tree.predict(X_test)

# Calculate prediction probabilities for AUC-ROC score
y_test_pred_proba = loaded_decision_tree.predict_proba(X_test)[:, 1]

# Evaluate the performance on the test set
accuracy = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
classification_rep = classification_report(y_test, y_test_pred)
roc_auc = roc_auc_score(y_test, y_test_pred_proba)

# Output the results
print("Confusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(classification_rep)

print(f"\nTesting Accuracy: {accuracy}")
print(f"Testing AUC-ROC Score: {roc_auc}")


Validation Confusion Matrix:
[[125288   1979]
 [  1874 125523]]
Validation Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.98    127267
           1       0.98      0.99      0.98    127397

    accuracy                           0.98    254664
   macro avg       0.98      0.98      0.98    254664
weighted avg       0.98      0.98      0.98    254664

Validation AUC-ROC Score: 0.9848956272610043
Confusion Matrix:
[[232178   4854]
 [  3648  21030]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98    237032
           1       0.81      0.85      0.83     24678

    accuracy                           0.97    261710
   macro avg       0.90      0.92      0.91    261710
weighted avg       0.97      0.97      0.97    261710


Testing Accuracy: 0.9675136601581904
Testing AUC-ROC Score: 0.9160439595747317


## 2. Random Forest

In [ ]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training set
rf_model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [ ]:
y_val_pred = rf_model.predict(X_val)

print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("\nClassification Report:")
print(classification_report(y_val, y_val_pred))



Confusion Matrix:
[[124839   2428]
 [   306 127091]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99    127267
           1       0.98      1.00      0.99    127397

    accuracy                           0.99    254664
   macro avg       0.99      0.99      0.99    254664
weighted avg       0.99      0.99      0.99    254664



In [ ]:
# Calculate AUC-ROC score
roc_auc = roc_auc_score(y_val, rf_model.predict_proba(X_val)[:, 1])
print(f"\nValidation AUC-ROC Score: {roc_auc}")

# Feature importance (optional, to check which features are important)
importances = rf_model.feature_importances_
feature_importance = sorted(zip(importances, X_train.columns), reverse=True)
print("\nFeature Importances:")
for importance, name in feature_importance:
    print(f"{name}: {importance}")



Validation AUC-ROC Score: 0.9987704062876975

Feature Importances:
Column18: 0.5829721417845564
Column1: 0.15503635328446805
Column4: 0.07124418665729271
Column8: 0.0470977126648928
Column3: 0.04466343687265631
Column12: 0.02039748526689398
Column11: 0.016856502764533432
Column13: 0.015985821346891728
Column2: 0.009881142156405337
Column6: 0.009199877266087848
Column0: 0.0067539641138394625
Column10: 0.0059984691894439945
Column17: 0.0059051461841919195
Column7: 0.004177621799887495
Column5: 0.0021077403946048053
Column15: 0.0010658963863496725
Column14: 0.000656501867004125
Column21: 0.0
Column20: 0.0
Column19: 0.0
Column16: 0.0


In [ ]:
joblib.dump(rf_model, 'rf_model.pkl')
# Assuming your testing_df is already loaded and cleaned
X_test = testing_df.drop(columns=['ID', 'target'])  # Remove ID and target from test features
y_test = testing_df['target']  # Use the target column for test labels

# Load the saved Decision Tree model
loaded_decision_tree = joblib.load('rf_model.pkl')

# Predict on testing data
y_test_pred = loaded_decision_tree.predict(X_test)

# Calculate prediction probabilities for AUC-ROC score
y_test_pred_proba = loaded_decision_tree.predict_proba(X_test)[:, 1]

# Evaluate the performance on the test set
accuracy = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
classification_rep = classification_report(y_test, y_test_pred)
roc_auc = roc_auc_score(y_test, y_test_pred_proba)

# Output the results
print("Confusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(classification_rep)

print(f"\nTesting Accuracy: {accuracy}")
print(f"Testing AUC-ROC Score: {roc_auc}")

Confusion Matrix:
[[231085   5947]
 [   696  23982]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.99    237032
           1       0.80      0.97      0.88     24678

    accuracy                           0.97    261710
   macro avg       0.90      0.97      0.93    261710
weighted avg       0.98      0.97      0.98    261710


Testing Accuracy: 0.9746169424171793
Testing AUC-ROC Score: 0.9927286843795101


In [ ]:
pip install xgboost

## 3. XG Boost

In [ ]:
xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')

# Train the model on the resampled training data
xgb_model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [13:50:06] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

In [ ]:
y_val_pred = xgb_model.predict(X_val)

# Evaluate the model on the validation set
val_conf_matrix = confusion_matrix(y_val, y_val_pred)
val_class_report = classification_report(y_val, y_val_pred)
val_auc_roc = roc_auc_score(y_val, xgb_model.predict_proba(X_val)[:, 1])

print("Validation Confusion Matrix:")
print(val_conf_matrix)

print("\nValidation Classification Report:")
print(val_class_report)

print(f"Validation AUC-ROC Score: {val_auc_roc}")



Validation Confusion Matrix:
[[125077   2190]
 [   533 126864]]

Validation Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99    127267
           1       0.98      1.00      0.99    127397

    accuracy                           0.99    254664
   macro avg       0.99      0.99      0.99    254664
weighted avg       0.99      0.99      0.99    254664

Validation AUC-ROC Score: 0.9990943784024466


In [ ]:
joblib.dump(xgb_model, 'xg_model.pkl')
# Assuming your testing_df is already loaded and cleaned
X_test = testing_df.drop(columns=['ID', 'target'])  # Remove ID and target from test features
y_test = testing_df['target']  # Use the target column for test labels

# Load the saved Decision Tree model
xgb_model = joblib.load('xg_model.pkl')

# Predict on testing data
y_test_pred = xgb_model.predict(X_test)

# Calculate prediction probabilities for AUC-ROC score
y_test_pred_proba = xgb_model.predict_proba(X_test)[:, 1]

# Evaluate the performance on the test set
accuracy = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
classification_rep = classification_report(y_test, y_test_pred)
roc_auc = roc_auc_score(y_test, y_test_pred_proba)

# Output the results
print("Confusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(classification_rep)

print(f"\nTesting Accuracy: {accuracy}")
print(f"Testing AUC-ROC Score: {roc_auc}")

Confusion Matrix:
[[231802   5230]
 [  1106  23572]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99    237032
           1       0.82      0.96      0.88     24678

    accuracy                           0.98    261710
   macro avg       0.91      0.97      0.93    261710
weighted avg       0.98      0.98      0.98    261710


Testing Accuracy: 0.975789996561079
Testing AUC-ROC Score: 0.9935382784775314


# Support Vector Machine (SVM) Model Implementation

In [ ]:
# Step 1: Initialize and train the SVM model
svm_model = SVC(random_state=42, probability=True)

In [ ]:
# Train the model
svm_model.fit(X_train, y_train)

In [ ]:
# Step 2: Predict on the validation set
y_val_pred = svm_model.predict(X_val)

In [ ]:
# Step 3: Evaluate the model on the validation set
print("Validation Confusion Matrix (SVM):")
print(confusion_matrix(y_val, y_val_pred))

print("\nValidation Classification Report (SVM):")
print(classification_report(y_val, y_val_pred))

In [ ]:
# Step 4: Calculate AUC-ROC Score for SVM
y_val_proba = svm_model.predict_proba(X_val)[:, 1]
roc_auc = roc_auc_score(y_val, y_val_proba)
print("Validation AUC-ROC Score (SVM):", roc_auc)

In [ ]:
# Step 5: Plot the ROC Curve for SVM
fpr, tpr, thresholds = roc_curve(y_val, y_val_proba)
plt.plot(fpr, tpr, label=f"SVM (AUC = {roc_auc:.2f})")
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (SVM)')
plt.legend(loc='best')
plt.show()

In [ ]:
# Step 6: Learning Curves for SVM
train_sizes, train_scores, val_scores = learning_curve(svm_model, X_resampled, y_resampled, cv=5)

train_scores_mean = train_scores.mean(axis=1)
val_scores_mean = val_scores.mean(axis=1)

In [ ]:
plt.plot(train_sizes, train_scores_mean, label='Training Score (SVM)')
plt.plot(train_sizes, val_scores_mean, label='Validation Score (SVM)')
plt.xlabel('Training Size')
plt.ylabel('Score')
plt.title('Learning Curves (SVM)')
plt.legend()
plt.show()

In [ ]:
joblib.dump(svm_model, 'svm_model.pkl')
# Assuming your testing_df is already loaded and cleaned
X_test = testing_df.drop(columns=['ID', 'target'])  # Remove ID and target from test features
y_test = testing_df['target']  # Use the target column for test labels

# Load the saved Decision Tree model
loaded_decision_tree = joblib.load('svm_model.pkl')

# Predict on testing data
y_test_pred = loaded_decision_tree.predict(X_test)

# Calculate prediction probabilities for AUC-ROC score
y_test_pred_proba = loaded_decision_tree.predict_proba(X_test)[:, 1]

# Evaluate the performance on the test set
accuracy = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
classification_rep = classification_report(y_test, y_test_pred)
roc_auc = roc_auc_score(y_test, y_test_pred_proba)

# Output the results
print("Confusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(classification_rep)

print(f"\nTesting Accuracy: {accuracy}")
print(f"Testing AUC-ROC Score: {roc_auc}")

#Ensemble Using Voting Classifier

In [ ]:
# Step 1: Create the Voting Classifier with 'soft' voting
voting_clf = VotingClassifier(estimators=[
    ('logistic', logistic_reg),
    ('decision_tree', decision_tree),
    ('svm', svm_model),
    ('xgboost', xgboost_model),
    ('random_forest', random_forest)
], voting='soft')  # Soft voting for probability-based aggregation

In [ ]:
# Step 2: Split the data into training and validation sets
# Assuming X_resampled and y_resampled are the balanced features and target after using SMOTE or another method
X_train, X_val, y_train, y_val = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

In [ ]:
# Step 4: Train the Voting Classifier on the training set
voting_clf.fit(X_train, y_train)

In [ ]:
# Step 5: Predict on the validation set
y_val_pred = voting_clf.predict(X_val)

In [ ]:
# Step 6: Evaluate the ensemble model on the validation set
print("Validation Confusion Matrix (Ensemble):")
print(confusion_matrix(y_val, y_val_pred))


print("\nValidation Classification Report (Ensemble):")
print(classification_report(y_val, y_val_pred))

In [ ]:
# Step 7: Calculate AUC-ROC Score for the Voting Classifier
y_val_proba = voting_clf.predict_proba(X_val)[:, 1]
roc_auc = roc_auc_score(y_val, y_val_proba)
print("Validation AUC-ROC Score (Ensemble):", roc_auc)

In [ ]:
# Step 8: Plot the ROC Curve for the Voting Classifier
fpr, tpr, thresholds = roc_curve(y_val, y_val_proba)
plt.plot(fpr, tpr, label=f"Voting Classifier (AUC = {roc_auc:.2f})")
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (Voting Classifier)')
plt.legend(loc='best')
plt.show()

In [ ]:
# Step 9: Learning Curves for the Voting Classifier
train_sizes, train_scores, val_scores = learning_curve(voting_clf, X_resampled, y_resampled, cv=5)

train_scores_mean = train_scores.mean(axis=1)
val_scores_mean = val_scores.mean(axis=1)

In [ ]:
plt.plot(train_sizes, train_scores_mean, label='Training Score (Ensemble)')
plt.plot(train_sizes, val_scores_mean, label='Validation Score (Ensemble)')
plt.xlabel('Training Size')
plt.ylabel('Score')
plt.title('Learning Curves (Voting Classifier)')
plt.legend()
plt.show()

In [ ]:
# Step 10: Test Set Evaluation (Optional)
# Assuming the test set is loaded as 'testing_df'
X_test = testing_df.drop(columns=['ID', 'target'])
y_test_true = testing_df['target']

In [ ]:
# Predict on the test set
y_test_pred = voting_clf.predict(X_test)

In [ ]:
# Evaluate on the test set
print("Test Confusion Matrix:")
print(confusion_matrix(y_test_true, y_test_pred))

print("\nTest Classification Report:")
print(classification_report(y_test_true, y_test_pred))

In [ ]:
# Calculate AUC-ROC on the test set
roc_auc_test = roc_auc_score(y_test_true, voting_clf.predict_proba(X_test)[:, 1])
print("\nTest AUC-ROC Score:", roc_auc_test)

In [ ]:
# Plot ROC Curve for the test set
fpr_test, tpr_test, thresholds_test = roc_curve(y_test_true, voting_clf.predict_proba(X_test)[:, 1])
plt.plot(fpr_test, tpr_test, label=f"Voting Classifier Test (AUC = {roc_auc_test:.2f})")
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Test ROC Curve')
plt.legend(loc='best')
plt.show()